version: "3.9"
services:
  registry:
    container_name: docker-registry
    restart: unless-stopped
    image: registry:2
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/kronshtadt.pem
      REGISTRY_HTTP_TLS_KEY: /certs/kronshtadt.key
    ports:
      - 5000:5000
    volumes:
#      - /srv/docker-regestry/images:/var/lib/registry
      - /var/lib:/var/lib/registry
#      - docker-registry-data:/var/lib/registry
      - ./certs:/certs
#volumes:
#  docker-registry-data: {}