version: "3.9"
services:
  registry:
    container_name: docker-registry
    restart: unless-stopped
    image: registry:2
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/kronshtadt.crt
      REGISTRY_HTTP_TLS_KEY: /certs/kronshtadt.key
    ports:
      - 5000:5000
    volumes:
      - /srv/docker-regestry/images/docker/registry/v2:/var/lib/registry
      - ./certs:/certs
