version: "3.9"
services:
  iperf:
    image: networkstatic/iperf3
#    image: xridge/iperf3:3.7.0
    restart: unless-stopped
    container_name: iperf3
    ports:
      - "5201:5201/tcp"
      - "5201:5201/udp"
    command: -s
