version: "3.9"
services:
  proxy-repo:
    image: zhusj/apt-cacher-ng
    container_name: repo-debian-ubuntu
    ports:
      - '3142:3142'
    restart: unless-stopped
    volumes:
      - '/srv/apt-cacher-ng/sources.list.d:/etc/apt/sources.list.d/'
    
