---
version: '3'

services:
  apt-cacher-ng:
#    image: mollien/apt-cacher-ng
    image: docker pull sameersbn/apt-cacher-ng:3.7.4-20220421
#    image: zhusj/apt-cacher-ng:202210191826
    container_name: apt-cacher-ng
    restart: unless-stopped
    ports:
      - "3142:3142"
    volumes:
      - apt-cacher-ng:/var/cache/apt-cacher-ng
      - /srv/apt-cacher-ng/sources.list.d:/etc/apt/sources.list.d/
    
volumes:
  apt-cacher-ng: