version: "3.9"

services:
  py-app:
    image: evgvac/py-app:v0.11
    container_name: py-app
    restart: unless-stopped
    ports:
      - '5000:5000'
#    expose:
#      - 5000
#    networks:
#      - monitoring
  
  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
#    expose:
#      - 9090
#    networks:
#      - monitoring
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    restart: unless-stopped
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8080:8080'
#    expose:
#      - 8080
#    networks:
#      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.5.0
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - '9100:9100'    
#    expose:
#      - 9100
#    networks:
#      - monitoring

  grafana:
    image: grafana/grafana:9.4.1
    container_name: grafana
    restart: unless-stopped
#    volumes:
#      - ./grafana:/var/lib/grafana
#      - ./grafana/provisioning/:/etc/grafana/provisioning/
    volumes:
      - ./grafana/provisioning/datasources/grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./grafana/grafana_config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
#    expose:
#      - 3000
#    networks:
#      - monitoring


volumes:
  prometheus_data: {}
  grafana_data: {}